name = "Integrated North"
author = "Ozoku"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50893e5eebb2785ceca3f2b8270ad63b2cd34a387b5b9c45a8b0dae9e727d2e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
