name = "Integrated North"
author = "Ozoku"
version = "0.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70d7f3c4ae37bec26fa35860831f3f028c5d0867b08ec947dab02dda05b24e0c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
