name = "Integrated North"
author = "Ozoku"
version = "0.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44cca04875ec47f2f8ece7d8c963de48398f4aa271b25b0ded26bec3e929bc0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
