#List of entity configurations
[[entities]]
  entity = "minecraft:creeper"
  minTier = 0
  maxTier = 4
  presetAffixes = []
  affixList = ["champions:knocking", "champions:wounding", "champions:paralyzing", "champions:molten"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "minecraft:ender_dragon"
  minTier = 2
  maxTier = 4
  presetAffixes = []
  affixList = ["champions:infested", "champions:magnetic", "champions:knocking"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "minecraft:wither"
  minTier = 0
  maxTier = 1
  presetAffixes = []
  affixList = ["champions:lively"]
  affixPermission = "BLACKLIST"
